[package]
name = "weverywhere"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.9"

serde_json = "1.0"
serde_cbor = "0.11"
serde_bare = "0.5"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.wasmtime]
version = "38"


