[package]
name = "weverywhere"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.wasmtime]
version = "38"


