

[identity]
name = "Jeff's Test Server"
key = "/tmp/weverywhere-test.pem"

# This block may be duplicated, it is a list of objects with the property 'path'. All include paths will be glob-resolved and
# configuration is appled in-order of traversal.
[[includes]]
path = "/etc/weverywhere.d/*.toml"

